### ISSUE TITLE
Quick start 

### ISSUE THREAD

**Issue by Thijxx** [snowplow/snowplow-tracking-cli#26]
Hi, I followed the quick start and then tried the first Example and it failed because it cannot find `snowplowtrk` so I think a step is missing.

**Comment by paulboocock** [comment]
Hey @Thijxx 
The Quick Start on this repository is aimed at maintainers rather than users of the app which means you don't need to build it to use it, you can download the prebuilt binaries. 

Looking at the quick start though, if you have built it, then it should be available under the `build` folder.

Our more comprehensive docs can be found here: https://docs.snowplowanalytics.com/docs/collecting-data/collecting-from-own-applications/snowplow-tracking-cli/

I'll look to update the README to make it clearer.

**Comment by paulboocock** [comment]
This definitely slipped off my todo list, sorry about that. The README has now been updated though and is hopefully clearer, thanks for your issue.
