### ISSUE TITLE
Collector domain directory support

### ISSUE THREAD

**Issue by Thijxx** [snowplow/snowplow-tracking-cli#27]
Hi, it seems that I cannot use a collector running on DOMAIN/DIRECTORY. The client tells me to check the endpoint but if I se CURL it's just fine.

**Comment by Thijxx** [comment]
command
`./snowplow-tracking-cli --collector mycollector.something.net/collector --appid thijs --method POST --schema iglu:com.snowplowanalytics.snowplow/event/jsonschema/1-0-0 --json "{\"hello\":\"world\"}"`

response
`error: event failed to send, check your collector endpoint and try again`

**Comment by Thijxx** [comment]
it returns a 404, but when I use the Python Tracker it can POST so I'm a bit confused

**Comment by paulboocock** [comment]
Can you share your Python Tracker Emitter and Tracker initialisation code? I'll see if I can spot any differences.

**Comment by paulboocock** [comment]
The most obvious difference I can see here is that the default configuration of the Python Trackers Emitter is to send events as GET requests, whereas your current Tracking CLI example is using POST. 
Not only is this a different HTTP Request type, this also means they end up being sent to a slightly different URL:
POST: http://mydomain.net/collector/com.snowplowanalytics.snowplow/tp2
GET: http://mydomain.net/collector/i

I'm going to close this now as it seems to be a set up issue rather than a bug, but I'm happy to continue chatting here or we could move it to our [Discourse forum](https://discourse.snowplowanalytics.com/) where there might be a little more help floating around, particularly if you'd like to discuss your infra.
